CC=g++
main: main.cpp headers/utils.cpp headers/utils.h headers/game_objects/screen.cpp headers/game_objects/pallet.cpp headers/game_objects/dot.cpp headers/game_objects/ball.cpp headers/game_objects/game_objects.h headers/input.cpp headers/input.h
	$(CC) main.cpp headers/utils.cpp headers/game_objects/screen.cpp headers/game_objects/pallet.cpp headers/game_objects/dot.cpp  headers/game_objects/ball.cpp headers/input.cpp -o main
